import React, { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { Calendar, List, ArrowLeft, Filter, CheckCircle, Clock, AlertCircle, Loader2, RotateCcw, RotateCw, Edit2, Check, X, Copy, GitCompare } from 'lucide-react';
import { PLANNING_REFERENCE_DATE, PLANNING_REFERENCE_DATE_STR } from '@/lib/planningDate';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import PhaseIndicator from '@/components/schedulo/PhaseIndicator';
import StepHeader from '@/components/schedulo/StepHeader';
import ContextChat from '@/components/schedulo/ContextChat';
import { motion } from 'framer-motion';

const HOUR_SLOTS = Array.from({ length: 14 }, (_, i) => i + 7); // 7am to 8pm

export default function PlanGeneration() {
  const { planId } = useParams();
  const navigate = useNavigate();
  const [plan, setPlan] = useState(null);
  const [tasks, setTasks] = useState([]);
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [view, setView] = useState('calendar');
  const [filter, setFilter] = useState('all');
  const [weekOffset, setWeekOffset] = useState(0);
  const [undoStack, setUndoStack] = useState([]);
  const [redoStack, setRedoStack] = useState([]);
  const [scenarios, setScenarios] = useState([]);
  const [activeScenario, setActiveScenario] = useState(0);
  const [showComparison, setShowComparison] = useState(false);

  useEffect(() => { loadData(); }, [planId]);

  // Auto-generate if not yet generated
  const hasAutoGenerated = React.useRef(false);

  const loadData = async () => {
    const p = await base44.entities.StudyPlan.get(planId);
    setPlan(p);
    const t = await base44.entities.StudyTask.filter({ plan_id: planId });
    setTasks(t);
    const alreadyGenerated = t.some(task => task.scheduled_date);
    if (alreadyGenerated) {
      setGenerated(true);
    } else if (!hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      // Auto-start generation
      setTimeout(() => generatePlanWithData(p, t), 100);
    }
    if (p.scenarios?.length) setScenarios(p.scenarios);
  };

  const generatePlanWithData = async (p, allTasks) => {
    setGenerating(true);
    const prefs = p.preferences || {};
    const calEvents = p.calendar_events || [];
    const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

    // Build human-readable availability from schedule
    const daySchedule = prefs.schedule || {};
    const maxHoursPerDay = prefs.max_hours || 6;
    const availabilityLines = DAYS.map(day => {
      const d = daySchedule[day];
      if (!d || d.noStudy) return `  ${day}: No study`;
      return `  ${day}: ${d.start || '09:00'}–${d.end || '18:00'} (max ${maxHoursPerDay}h)`;
    }).join('\n');

    // Build blocked time description from calendar events
    const blockedLines = calEvents.length > 0
      ? calEvents.map(e => `  - ${e.name}: ${e.day_of_week || ''} ${e.start_time || ''}${e.end_time ? '–' + e.end_time : ''} [${e.is_recurring ? 'every week' : e.start_date}]`).join('\n')
      : '  None';

    const prompt = `You are a study plan scheduler. Generate a complete time-blocked study schedule that covers ALL provided tasks.

IMPORTANT: Today's planning reference date is ${PLANNING_REFERENCE_DATE_STR}. Use this as "today". Do not treat any semester dates as past.

Study Period: ${p.start_date} to ${p.end_date}
Break Duration: ${prefs.break_duration || 15} minutes between sessions

DAILY STUDY AVAILABILITY (when student CAN study):
${availabilityLines}

BLOCKED TIMES (student is unavailable — NEVER schedule study here):
${blockedLines}

TASKS TO SCHEDULE (schedule ALL of them):
${allTasks.map(t => `- ID: ${t.id} | "${t.title}" (${t.course_name}) | ${t.estimated_hours}h | Priority: ${t.priority} | Deadline: ${t.deadline || 'none'} | Type: ${t.task_type}`).join('\n')}

SCHEDULING RULES:
1. Schedule EVERY task — the schedule must be complete with no tasks left unscheduled.
2. Respect blocked times — never schedule during a blocked period.
3. Only schedule within the daily availability windows listed above.
4. Max ${maxHoursPerDay} hours of study per day.
5. Prioritize tasks by: deadline proximity first, then priority level.
6. Distribute workload evenly across the semester — don't pile everything at the end.
7. Split tasks >2h into multiple sessions across different days.
8. For tasks with deadlines, ensure they are fully scheduled well before the deadline.
9. Respect the recommended study order — schedule earlier-ordered tasks first within each course.

Return JSON with a "schedule" array containing ALL tasks scheduled. Each item:
- task_id (string — must match an ID from the task list above)
- scheduled_date (YYYY-MM-DD, must be within study period)
- scheduled_start (HH:MM, within the day's availability window)
- scheduled_end (HH:MM, within the day's availability window)
- explanation (brief reason for this slot)`;

    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt,
        response_json_schema: {
          type: "object",
          properties: {
            schedule: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  task_id: { type: "string" },
                  scheduled_date: { type: "string" },
                  scheduled_start: { type: "string" },
                  scheduled_end: { type: "string" },
                  explanation: { type: "string" }
                }
              }
            }
          }
        },
        model: 'claude_sonnet_4_6'
      });

      const schedule = result.schedule || [];
      const bulkUpdates = schedule
        .filter(item => allTasks.find(t => t.id === item.task_id))
        .map(item => ({
          id: item.task_id,
          scheduled_date: item.scheduled_date,
          scheduled_start: item.scheduled_start,
          scheduled_end: item.scheduled_end,
          explanation: item.explanation
        }));
      if (bulkUpdates.length > 0) {
        await base44.entities.StudyTask.bulkUpdate(bulkUpdates);
      }

      const updatedTasks = await base44.entities.StudyTask.filter({ plan_id: planId });
      setTasks(updatedTasks);
      setScenarios([{ name: 'Scenario 1', tasks: updatedTasks.map(t => ({ id: t.id, scheduled_date: t.scheduled_date, scheduled_start: t.scheduled_start, scheduled_end: t.scheduled_end })) }]);
      await base44.entities.StudyPlan.update(planId, {
        scenarios: [{ name: 'Scenario 1', created: new Date().toISOString() }],
        step: 8
      });
      setGenerated(true);
    } catch (e) {
      console.error(e);
    }
    setGenerating(false);
  };

  const generatePlan = async () => {
    const p = await base44.entities.StudyPlan.get(planId);
    const allTasks = await base44.entities.StudyTask.filter({ plan_id: planId });
    await generatePlanWithData(p, allTasks);
  };

  const getWeekDates = () => {
    if (!plan?.start_date) return [];
    const start = new Date(plan.start_date);
    start.setDate(start.getDate() + weekOffset * 7);
    const startDay = start.getDay();
    const monday = new Date(start);
    monday.setDate(start.getDate() - ((startDay + 6) % 7));
    return Array.from({ length: 7 }, (_, i) => {
      const d = new Date(monday);
      d.setDate(monday.getDate() + i);
      return d;
    });
  };

  const getFilteredTasks = () => {
    if (filter === 'study') return tasks.filter(t => t.scheduled_date);
    if (filter === 'deadlines') return tasks.filter(t => t.deadline);
    return tasks;
  };

  const weekDates = getWeekDates();
  const dayNames = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  const filteredTasks = getFilteredTasks();

  const getTasksForDateAndHour = (date, hour) => {
    const dateStr = date.toISOString().split('T')[0];
    return filteredTasks.filter(t => {
      if (t.scheduled_date !== dateStr) return false;
      const startHour = parseInt(t.scheduled_start?.split(':')[0] || '0');
      return startHour === hour;
    });
  };

  const getEventsForDateAndHour = (date, hour) => {
    if (!plan?.calendar_events) return [];
    const dateStr = date.toISOString().split('T')[0];
    return plan.calendar_events.filter(e => {
      if (e.date !== dateStr && e.recurrence !== 'weekly') return false;
      if (e.recurrence === 'weekly') {
        const eventDay = new Date(e.date).getDay();
        if (date.getDay() !== eventDay) return false;
      } else if (e.date !== dateStr) return false;
      const startHour = parseInt(e.start_time?.split(':')[0] || '0');
      return startHour === hour;
    });
  };

  const confirmPlan = async () => {
    await base44.entities.StudyPlan.update(planId, { status: 'active', phase: 'active', step: 9 });
    const toConfirm = tasks.filter(t => t.scheduled_date).map(t => ({ id: t.id, confirmed: true }));
    if (toConfirm.length > 0) {
      await base44.entities.StudyTask.bulkUpdate(toConfirm);
    }
    navigate(`/plan/${planId}/active`);
  };

  const typeColors = {
    reading: 'bg-blue-100 border-blue-300 text-blue-800',
    assignment: 'bg-purple-100 border-purple-300 text-purple-800',
    exercise: 'bg-green-100 border-green-300 text-green-800',
    revision: 'bg-amber-100 border-amber-300 text-amber-800',
    test: 'bg-red-100 border-red-300 text-red-800',
    project_work: 'bg-indigo-100 border-indigo-300 text-indigo-800',
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50">
      <PhaseIndicator currentPhase="generation" currentStep={8} />
      <div className="max-w-6xl mx-auto px-4 py-8">
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
          <StepHeader
            icon={Calendar}
            title="Your Study Plan"
            description={generated ? "Review your generated study plan. You can edit, reschedule, or compare scenarios." : "I'll generate a time-blocked study schedule based on your tasks and preferences."}
          />

          {generating && (
            <div className="bg-white rounded-xl border border-blue-100 p-8 shadow-sm text-center mb-6">
              <Loader2 className="w-10 h-10 animate-spin text-blue-500 mx-auto mb-3" />
              <p className="text-gray-600 font-medium">Generating your personalized study plan...</p>
              <p className="text-sm text-gray-400">Scheduling all tasks, respecting your availability and deadlines.</p>
              <div className="mt-4 w-full bg-gray-100 rounded-full h-1.5">
                <div className="bg-blue-500 h-1.5 rounded-full animate-pulse" style={{ width: '60%' }} />
              </div>
            </div>
          )}

          {generated && !generating && (
            <>
              {/* Toolbar */}
              <div className="flex flex-wrap gap-2 items-center justify-between mb-4">
                <div className="flex gap-2">
                  <Button variant={view === 'calendar' ? 'default' : 'outline'} size="sm" onClick={() => setView('calendar')}>
                    <Calendar className="w-4 h-4 mr-1" /> Calendar
                  </Button>
                  <Button variant={view === 'list' ? 'default' : 'outline'} size="sm" onClick={() => setView('list')}>
                    <List className="w-4 h-4 mr-1" /> Task List
                  </Button>
                </div>
                <div className="flex gap-2">
                  <Select value={filter} onValueChange={setFilter}>
                    <SelectTrigger className="w-40"><Filter className="w-3.5 h-3.5 mr-1" /><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">Show all</SelectItem>
                      <SelectItem value="study">Study tasks only</SelectItem>
                      <SelectItem value="deadlines">Deadlines only</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              {view === 'calendar' && (
                <>
                  {/* Week navigation */}
                  <div className="flex items-center justify-between mb-3">
                    <Button variant="ghost" size="sm" onClick={() => setWeekOffset(w => w - 1)}>← Previous</Button>
                    <span className="text-sm font-medium text-gray-600">
                      {weekDates[0]?.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} – {weekDates[6]?.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                    </span>
                    <Button variant="ghost" size="sm" onClick={() => setWeekOffset(w => w + 1)}>Next →</Button>
                  </div>

                  {/* Calendar grid */}
                  <div className="bg-white rounded-xl border border-blue-100 shadow-sm overflow-hidden mb-6">
                    <div className="grid grid-cols-8 border-b border-gray-100">
                      <div className="p-2 text-xs text-gray-400 text-center"></div>
                      {weekDates.map((d, i) => (
                        <div key={i} className={`p-2 text-center border-l border-gray-100 ${d.toDateString() === PLANNING_REFERENCE_DATE.toDateString() ? 'bg-blue-50' : ''}`}>
                          <p className="text-xs text-gray-400">{dayNames[i]}</p>
                          <p className={`text-sm font-semibold ${d.toDateString() === PLANNING_REFERENCE_DATE.toDateString() ? 'text-blue-600' : 'text-gray-700'}`}>{d.getDate()}</p>
                        </div>
                      ))}
                    </div>
                    <div className="max-h-[500px] overflow-y-auto">
                      {HOUR_SLOTS.map(hour => (
                        <div key={hour} className="grid grid-cols-8 border-b border-gray-50 min-h-[48px]">
                          <div className="p-1 text-xs text-gray-400 text-right pr-2 pt-1">{hour}:00</div>
                          {weekDates.map((d, i) => {
                            const dayTasks = getTasksForDateAndHour(d, hour);
                            const dayEvents = getEventsForDateAndHour(d, hour);
                            return (
                              <div key={i} className="border-l border-gray-50 p-0.5 relative">
                                {dayEvents.map((ev, j) => (
                                  <div key={`ev-${j}`} className="text-xs bg-gray-100 border border-gray-200 rounded px-1 py-0.5 mb-0.5 truncate text-gray-600">
                                    {ev.name}
                                  </div>
                                ))}
                                {dayTasks.map((task, j) => (
                                  <div key={`t-${j}`} className={`text-xs rounded px-1 py-0.5 mb-0.5 truncate border ${typeColors[task.task_type] || 'bg-gray-100 border-gray-200 text-gray-700'}`} title={`${task.title} (${task.course_name})`}>
                                    {task.title}
                                  </div>
                                ))}
                              </div>
                            );
                          })}
                        </div>
                      ))}
                    </div>
                  </div>
                </>
              )}

              {view === 'list' && (
                <div className="bg-white rounded-xl border border-blue-100 shadow-sm overflow-hidden mb-6">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="bg-gray-50 text-left text-xs text-gray-500 uppercase tracking-wider">
                        <th className="px-4 py-3">Course</th>
                        <th className="px-4 py-3">Task</th>
                        <th className="px-4 py-3">Date & Time</th>
                        <th className="px-4 py-3">Hours</th>
                        <th className="px-4 py-3">Deadline</th>
                        <th className="px-4 py-3">Priority</th>
                        <th className="px-4 py-3">Status</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-50">
                      {filteredTasks
                        .sort((a, b) => (a.scheduled_date || '').localeCompare(b.scheduled_date || ''))
                        .map(task => (
                        <tr key={task.id} className="hover:bg-blue-50/50">
                          <td className="px-4 py-3 text-gray-600">{task.course_name}</td>
                          <td className="px-4 py-3 font-medium text-gray-900">{task.title}</td>
                          <td className="px-4 py-3 text-gray-600">
                            {task.scheduled_date && `${task.scheduled_date} ${task.scheduled_start || ''}-${task.scheduled_end || ''}`}
                          </td>
                          <td className="px-4 py-3 text-gray-600">{task.estimated_hours}h</td>
                          <td className="px-4 py-3 text-gray-600">{task.deadline || '—'}</td>
                          <td className="px-4 py-3">
                            <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                              task.priority === 'high' ? 'bg-red-100 text-red-700' :
                              task.priority === 'medium' ? 'bg-amber-100 text-amber-700' :
                              'bg-green-100 text-green-700'
                            }`}>{task.priority}</span>
                          </td>
                          <td className="px-4 py-3">
                            <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                              task.status === 'completed' ? 'bg-emerald-100 text-emerald-700' :
                              task.status === 'in_progress' ? 'bg-blue-100 text-blue-700' :
                              task.status === 'postponed' ? 'bg-gray-100 text-gray-600' :
                              'bg-gray-100 text-gray-600'
                            }`}>{task.status}</span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}

              {/* Actions */}
              <div className="flex flex-wrap justify-between items-center gap-3">
                <div className="flex gap-2">
                  <Button variant="ghost" onClick={() => navigate(`/plan/${planId}/feasibility`)}>
                    <ArrowLeft className="w-4 h-4 mr-1" /> Back
                  </Button>
                  <Button variant="outline" size="sm" onClick={generatePlan}>
                    <RotateCcw className="w-4 h-4 mr-1" /> Re-generate
                  </Button>
                </div>
                <Button onClick={confirmPlan} className="bg-emerald-600 hover:bg-emerald-700">
                  <CheckCircle className="w-4 h-4 mr-1" /> Confirm and activate plan
                </Button>
              </div>
            </>
          )}
        </motion.div>
      </div>
      <ContextChat phase="plan" planId={planId} suggestions={[
        "Why is this task scheduled here?",
        "Can I move a task to another day?",
        "How do I compare different plan scenarios?"
      ]} />
    </div>
  );
}